ktor:
    application:
        modules:
            - com.khan366kos.ApplicationKt.module
    deployment:
        port: 8080

scheduler:
    enabled: true
    schedule:
        time: "09:29"
        timezone: "Europe/Moscow"
